In [1]:
import tensorflow as tf
print(tf.__version__)

2.10.1


# Tensor

In [2]:
print(tf.add(1, 2))
print(tf.add([1, 2], [3, 4]))
print(tf.square(5))
print(tf.reduce_sum([1, 2, 3,]))

print(tf.square(2) + tf.square(3))

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([4 6], shape=(2,), dtype=int32)
tf.Tensor(25, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(13, shape=(), dtype=int32)


In [3]:
x = tf.matmul([[1]], [[2, 3]])
print(x)
print(x.shape)
print(x.dtype)

tf.Tensor([[2 3]], shape=(1, 2), dtype=int32)
(1, 2)
<dtype: 'int32'>


# Numpy 호환

In [4]:
import numpy as np

ndarray = np.ones([3, 3])

tensor = tf.multiply(ndarray, 42)
print(tensor)

print(np.add(tensor, 1))

print(tensor.numpy())

tf.Tensor(
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]], shape=(3, 3), dtype=float64)
[[43. 43. 43.]
 [43. 43. 43.]
 [43. 43. 43.]]
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]]


# GPU Acceleration

In [6]:
x = tf.random.uniform([3, 3])

print(tf.config.list_physical_devices('GPU'))
print(x.device.endswith("GPU:0"))

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
True


# 명시적 장치 배치

In [7]:
import time

def time_matmul(x):
    start = time.time()
    for loop in range(10):
        tf.matmul(x, x)

    result = time.time() - start
    print(f"10 loops: {1000*result:0.2f}ms")

print("On CPU")
with tf.device("CPU:0"):
    x = tf.random.uniform([1000, 1000])
    assert x.device.endswith("CPU:0")
    time_matmul(x)

if tf.config.list_physical_devices("GPU"):
    print("On GPU")
    with tf.device("GPU:0"):
        x = tf.random.uniform([1000, 1000])
        assert x.device.endswith("GPU:0")
        time_matmul(x)


On CPU
10 loops: 99.53ms
On GPU
10 loops: 2733.89ms


In [12]:
ds_tensors = tf.data.Dataset.from_tensor_slices([1, 2, 3, 4, 5, 6])

import tempfile
_, filename = tempfile.mkstemp()

with open(filename, "w") as f:
    f.write("""Line 1
Line 2
Line3
    """)
    ds_file = tf.data.TextLineDataset(filename)

In [13]:
ds_tensors = ds_tensors.map(tf.square).shuffle(2).batch(2)
ds_file = ds_file.batch(2)

In [14]:
for x in ds_tensors:
    print(x)

tf.Tensor([1 9], shape=(2,), dtype=int32)
tf.Tensor([16 25], shape=(2,), dtype=int32)
tf.Tensor([36  4], shape=(2,), dtype=int32)


In [15]:
for x in ds_file:
    print(x)

tf.Tensor([b'Line 1' b'Line 2'], shape=(2,), dtype=string)
tf.Tensor([b'Line3' b'    '], shape=(2,), dtype=string)
